### ISSUE TITLE
[BUG] Legacy Editor warning appears even if Legacy Editor is disabled

### ISSUE THREAD

**Issue by arnaldop** [vslinko/obsidian-zoom#71] opened 2022-08-07 16:01 UTC
**Describe the bug**
1. I installed a new version of Obsidian with a brand new Vault.
2. Legacy Editor Mode was disabled by default, because it is deprecated.
3. Every time I open Obsidian, I get Zoom's warning about the legacy editor not being supported.

**To Reproduce**
1. Install new Obsidian
2. Create new Vault
3. Install Zoom
4. Restart Obsidian
5. See warning, even though Obsidian disables legacy editor by default

**Expected behavior**
No warning if legacy editor is already disabled.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Obsidian Version: 0.15.9
 - Plugin Version: 0.3.0

**Comment by arnaldop** [comment] 2022-08-07 16:44
PR https://github.com/vslinko/obsidian-zoom/pull/72

**Comment by lukemt** [comment] 2022-08-10 12:53
Quick way to fix your installation: turn legacy editor on and off once. This will create the setting and make the warning go away. (The issue is otherwise the setting won't be present)

**Comment by arnaldop** [comment] 2022-08-10 13:12
> Quick way to fix your installation: turn legacy editor on and off once. This will create the setting and make the warning go away. (The issue is otherwise the setting won't be present)

@lukemt, this is not at all good UX. Good UX would be to not alert the user about a condition that is possible, but is not present in the system, thus drawing attention to inner workings that might never play out as such.

In other words, I didn't know about legacy editors, TypeScript configs, etc., until I kept getting the same warning for a condition that I was sure was not occurring in my system.

Shorter words: Don't warn user about things they are not doing. (And the fix is not to tell a user to do something else to make the unnecessary warning go away.)

**Comment by lukemt** [comment] 2022-08-10 16:18
Yeah true, just for now until a fix is available

**Comment by vslinko** [comment] 2022-08-14 09:28
@arnaldop @lukemt thank you all for your contributions. should be fixed in https://github.com/vslinko/obsidian-zoom/releases/tag/1.0.1

**Closed by vslinko** 2022-08-14 09:28 UTC
Labels: bug, difficulty:easy
