### ISSUE TITLE
Support for Live Preview?

### ISSUE THREAD

**Issue by cansar** [vslinko/obsidian-zoom#35] opened 2021-11-24 00:17 UTC
Hi,

I absolutely love the Zoom plugin and would love for it to be a Core plugin one day.

I know Live Preview is still really early but it would be great to have support for Zoom in it.

Thanks!

**Comment by vslinko** [comment] 2021-12-09 07:01
@cansar thank you for your feedback. closing this issue as duplicate of https://github.com/vslinko/obsidian-zoom/issues/34

**Closed by vslinko** 2021-12-09 07:01 UTC
