### ISSUE TITLE
[BUG] Unexpected text pushing behaviour while zoomed in

### ISSUE THREAD

**Issue by Glint-Eye** [vslinko/obsidian-zoom#77] opened 2022-09-24 11:38 UTC
I've already posted a discussion about this, but after further testing, i assume that this is a bug rather than a feature? As this behaviour doesnt' happen while zoomed into the very first heading of a document, but all other headings.

https://github.com/vslinko/obsidian-zoom/discussions/76#discussion-4416774

In short once again:
While zoomed into a heading, entering new list items only goes till the middle of the workspace. Each new entered list item inserted with Enter, will push the list up and leave half the workspace empty.

Here is an example:

![simplescreenrecorder-2022-09-24_13 02 58 mp4](https://user-images.githubusercontent.com/87322712/192095508-20a853f5-e799-4075-b1ce-f9202db9579c.gif)

The other text pushing behaviour happens while zoomed into a heading with a big list. When you create a new list item with Enter, the new list item will be pushed all the way to the top of the workspace and will be pushed off the workspace with the next hit of Enter.

Another example:

![simplescreenrecorder-2022-09-24_13 05 43 mp4](https://user-images.githubusercontent.com/87322712/192095695-728694a5-9284-4519-83e3-dcb3fe60b138.gif)

**Comment by freefaler** [comment] 2023-04-29 15:09
Indeed, I can confirm this problem. May be the only big one with this excellent plugin.
@vslinko , would pay something to get this fixed, because it really messes up working with zoomed items.

**Comment by vslinko** [comment] 2023-05-04 09:16
Fixed in https://github.com/vslinko/obsidian-zoom/releases/tag/1.1.2 and https://github.com/vslinko/obsidian-outliner/releases/tag/4.6.6

**Closed by vslinko** 2023-05-04 09:16 UTC
Labels: bug

**Comment by freefaler** [comment] 2023-05-04 09:49
Thanks @vslinko, looks like it's working correctly. 

My offer still stands, write me where I can send a tip. (paypal or crypto)

**Comment by vslinko** [comment] 2023-05-04 10:45
@freefaler I can't receive paypal or patreon. But I've created crypto account https://vslinko.cb.id/

**Comment by freefaler** [comment] 2023-05-04 12:01
@vslinko, sent some btc,  check your wallet in a couple of hours.

**Comment by vslinko** [comment] 2023-05-05 13:22
@freefaler Thank you very much for your support! Successfully received them.

**Comment by vslinko** [comment] 2023-05-09 21:52
@freefaler I mention my supporters in the README file. If you would like to be mentioned in the README, please send me what you would like to be called and what URL you would like to have.

**Comment by freefaler** [comment] 2023-05-10 11:43
Thanks @vslinko, there is no need if you ask me.
