### ISSUE TITLE
No Zoom command in the command palette

### ISSUE THREAD

**Issue by zen010101** [vslinko/obsidian-zoom#48] opened 2021-12-27 03:46 UTC
There is no command about Zoom in the Command Palette windows after installing the latest plugin version.

Obsidian: 0.13.14
Zoom: 0.2.6
Obsidian Editor: new, not lagacy editor

**Comment by vslinko** [comment] 2021-12-27 08:13
@zen010101 thank you for your feedback.

Could you please check if the plugin is enabled, restart Obsidian and look for commands again?

If it doesn't help, please enable "Debug mode" in the plugin settings, open Devtools by pressing <kbd>Command</kbd><kbd>Option</kbd><kbd>J</kbd> or <kbd>Control</kbd><kbd>Shift</kbd><kbd>J</kbd>, put your cursor on a header, press <kbd>Cmd</kbd><kbd>.</kbd>, copy output from Devtools here.

**Comment by zen010101** [comment] 2021-12-28 04:55
I enabled "Debug mode" in the plugin setting page, but not work. I can't see any window appears after that and I press `cmd+.` no  use too.

**Comment by zen010101** [comment] 2021-12-28 06:02
I seems it can't register the zoom command into the Obsidian command list

**Comment by vslinko** [comment] 2021-12-28 06:27
@zen010101 hmm. Try to reinstall the plug-in and restart Obsidian. Maybe it could help.

**Comment by TheAnsIs42** [comment] 2021-12-28 15:22
Hi, I just faced the same problem and the log from the console are shown below:
```
main.ts:20 Loading natural language date parser plugin
ObsidianOutlinerPlugin.ts:35 Loading obsidian-outliner
tslib.es6.js:74 Uncaught (in promise) Error: Could not call remote method 'setSpellCheckerLanguages'. Check that the method signature is correct. Underlying error: Invalid language code provided: "zh-CN" is not a valid language code
Underlying stack: Error: Invalid language code provided: "zh-CN" is not a valid language code
    at electron/js2c/browser_init.js:221:8665
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:221:5052)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10038)
    at Object.emit (events.js:315:20)

    at electron/js2c/browser_init.js:221:8693
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:221:5052)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10038)
    at Object.emit (events.js:315:20)
rejected @ tslib.es6.js:74
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
onload @ ObsidianOutlinerPlugin.ts:34
ObsidianZoomPlugin.ts:27 Loading obsidian-zoom
tslib.es6.js:74 Uncaught (in promise) Error: Could not call remote method 'setSpellCheckerLanguages'. Check that the method signature is correct. Underlying error: Invalid language code provided: "zh-CN" is not a valid language code
Underlying stack: Error: Invalid language code provided: "zh-CN" is not a valid language code
    at electron/js2c/browser_init.js:221:8665
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:221:5052)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10038)
    at Object.emit (events.js:315:20)

    at electron/js2c/browser_init.js:221:8693
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:221:5052)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10038)
    at Object.emit (events.js:315:20)
rejected @ tslib.es6.js:74
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
onload @ ObsidianZoomPlugin.ts:26
app.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
app.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```
Then I tried to change the language to English, which is the only language support spell check in Obsidian. And the command shows out and error log disappears. Everything works fine after I changed language into Chinese back again. But another problem is the dot appears in two places. As shown below:
![image](https://user-images.githubusercontent.com/44214674/147580962-baa6aff2-9956-4166-8bef-84f64c86cab8.png)
![image](https://user-images.githubusercontent.com/44214674/147580980-f4c414f1-8cba-49b0-8042-b0dfe2a80eb8.png)

**Comment by zen010101** [comment] 2021-12-30 14:00
> @zen010101 hmm. Try to reinstall the plug-in and restart Obsidian. Maybe it could help.

I uninstalled and reinstalled the plug-in and it didn't work :-( I fount no any command of it in the command palette.

**Comment by FelipeRearden** [comment] 2021-12-30 14:12
> > @zen010101 hmm. Try to reinstall the plug-in and restart Obsidian. Maybe it could help.
> 
> 
> 
> I uninstalled and reinstalled the plug-in and it didn't work :-( I fount no any command of it in the command palette.

Is Editor -> Fold heading toggle ON ?
Is Editor -> Fold Indent toggle ON ?

Are you in Source Mode or Live Preview when hitting command palette ?

**Comment by zen010101** [comment] 2021-12-30 16:25
![image](https://user-images.githubusercontent.com/60574100/147769883-cf8edea2-1530-4c8c-a46f-b2ed1874cddb.png)
![image](https://user-images.githubusercontent.com/60574100/147769909-13ba0c14-cfdd-40e7-8e59-b37d9debe7f2.png)
![image](https://user-images.githubusercontent.com/60574100/147769945-182c0a69-0785-4de6-9dae-4937845ab2bf.png)

**Comment by zen010101** [comment] 2021-12-30 16:26
![image](https://user-images.githubusercontent.com/60574100/147770012-86d730e6-6374-4f7a-9d76-ad54e8608df3.png)
![image](https://user-images.githubusercontent.com/60574100/147770030-848897e5-f6fc-49b7-bedf-273e0440d28c.png)

**Comment by watergua** [comment] 2022-01-05 09:31
HI, I'm having the the exact sample issue. My error message is same as @TheAnsIs42, and it happens everytime you unload and load the Plug-in. Switching language back to Englisch did not work, even re-install obsidian did not work
![image](https://user-images.githubusercontent.com/51666350/148194440-23d8000c-e334-4119-8db4-7c258786bcb8.png)

**Comment by zen010101** [comment] 2022-01-07 02:07
I found the Outliner plugin has the same problem :-(

**Comment by zen010101** [comment] 2022-01-07 02:49
the issue is solved by re-installing the obsidian and the plugin.

**Comment by vslinko** [comment] 2022-01-15 14:33
I still can't reproduce the issue. It seems to be a bug in Obsidian itself. Maybe the latest version of Obsidian has a fix.

@TheAnsIs42 @FelipeRearden @watergua Could you reinstall the latest version of Obsidian and try to install the plugin again?

**Comment by vslinko** [comment] 2022-01-21 06:28
@FelipeRearden thank you!

@TheAnsIs42 @watergua It would be great if you could test it as well.

**Comment by FelipeRearden** [comment] 2022-01-22 13:47
@vslinko 

From my experience version `2.0.8` still running perfect !

**Comment by watergua** [comment] 2022-01-26 08:59
I change my Windows system language to English and this issue is gone. Then I changed back, everything still fine. I have no idea how, but this could be a suggested fix.

**Comment by vslinko** [comment] 2022-01-27 08:31
Closing the issue. If someone still experiencing the problem, please create a new issue.

**Closed by vslinko** 2022-01-27 08:31 UTC
