### ISSUE TITLE
[feature request] remember zoom status

### ISSUE THREAD

**Issue by Jackiexiao** [vslinko/obsidian-zoom#69] opened 2022-04-23 03:48 UTC
when I switch to other page then switch back, zoom status reset to root page, is there any way to remember zoom status?

**Comment by vslinko** [comment] 2022-08-07 08:08
@Jackiexiao thank you for the feedback! closing as a duplicate of https://github.com/vslinko/obsidian-zoom/discussions/54

**Closed by vslinko** 2022-08-07 08:08 UTC
Labels: bug
